### ISSUE TITLE
all_routes_and_neighbours Exception

### ISSUE THREAD

**Issue by lecourtb** [mdeweerd/zha-toolkit#101]
While executing **all_routes_and_neighbours**:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1756, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/zha_toolkit/__init__.py", line 717, in toolkit_service
    raise handler_exception
  File "/config/custom_components/zha_toolkit/__init__.py", line 681, in toolkit_service
    await handler(
  File "/config/custom_components/zha_toolkit/__init__.py", line 766, in command_handler_default
    await default.default(
  File "/config/custom_components/zha_toolkit/default.py", line 33, in default
    await handler(app, listener, ieee, cmd, data, service, params, event_data)
  File "/config/custom_components/zha_toolkit/neighbours.py", line 79, in all_routes_and_neighbours
    await _routes_and_neighbours(device, listener)
  File "/config/custom_components/zha_toolkit/neighbours.py", line 43, in _routes_and_neighbours
    nbns = await asyncio.wait_for(async_get_neighbours(device), 180)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/config/custom_components/zha_toolkit/neighbours.py", line 167, in async_get_neighbours
    neighbors = val.NeighborTableList
AttributeError: 'Neighbors' object has no attribute 'NeighborTableList'`

Would be great to have it working !
Boris.

**Comment by mdeweerd** [comment]
Not something I use, but check out v0.8.22 .

Would be great to see some documentation !

**Comment by lecourtb** [comment]
Good job, thanks !
