### ISSUE TITLE
binds_remove_all and binds_remove_coordinator return invalid literal for int() with base 10: '0x4'

### ISSUE THREAD

**Issue by ErikApption** [mdeweerd/zha-toolkit#106]
I'm trying to unbind a Philips RWL 020 with
```yaml
service: zha_toolkit.binds_remove_all
data:
  ieee: 00:17:88:01:08:6E:7E:78
  tries: 100
  event_success: zha_event
  event_fail: zha_event
```

but this returns the following stack trace in the logs
```
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/zha_toolkit/binds.py:442
Integration: 🧰 ZHA Toolkit Service ([documentation](https://github.com/mdeweerd/zha-toolkit), [issues](https://github.com/mdeweerd/zha-toolkit/issues))
First occurred: 12:31:28 AM (5 occurrences)
Last logged: 1:18:03 AM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: invalid literal for int() with base 10: '0x4'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/srv/homeassistant/config/custom_components/zha_toolkit/__init__.py", line 717, in toolkit_service
    raise handler_exception
  File "/srv/homeassistant/config/custom_components/zha_toolkit/__init__.py", line 681, in toolkit_service
    await handler(
  File "/srv/homeassistant/config/custom_components/zha_toolkit/__init__.py", line 766, in command_handler_default
    await default.default(
  File "/srv/homeassistant/config/custom_components/zha_toolkit/default.py", line 33, in default
    await handler(app, listener, ieee, cmd, data, service, params, event_data)
  File "/srv/homeassistant/config/custom_components/zha_toolkit/binds.py", line 378, in unbind_coordinator
    await binds_remove_all(
  File "/srv/homeassistant/config/custom_components/zha_toolkit/binds.py", line 499, in binds_remove_all
    raise e
  File "/srv/homeassistant/config/custom_components/zha_toolkit/binds.py", line 442, in binds_remove_all
    dst_addr.nwk = t.uint16_t(binding["dst"]["group"])
  File "/srv/homeassistant/lib/python3.9/site-packages/zigpy/types/basic.py", line 91, in __new__
    n = super().__new__(cls, *args, **kwargs)
ValueError: invalid literal for int() with base 10: '0x4'
```

**Comment by mdeweerd** [comment]
Should be fixed - I refactored some code lately and the group value is store as a hex and has to be converted back to int for binds_remove_all.

See v0.8.24 .
