### ISSUE TITLE
Fail to reinitialize

### ISSUE THREAD

**Issue by Rudd-O** [mdeweerd/zha-toolkit#138]
```
Feb 06 15:28:36 assistant hass[581]: 2023-02-06 15:28:36.475 WARNING (MainThread) [zigpy.device] Device <Device model='FLOALT panel WS 30x90' manuf='IKEA of Sweden' nwk=0xF044 ieee=00:0d:6f:ff:fe:5b:2e:63 is_initialized=False> failed to initialize due to unexpected error
Feb 06 15:28:36 assistant hass[581]: Traceback (most recent call last):
Feb 06 15:28:36 assistant hass[581]:   File "/opt/assistant/lib64/python3.10/site-packages/zigpy/device.py", line 177, in initialize
Feb 06 15:28:36 assistant hass[581]:     await self._initialize()
Feb 06 15:28:36 assistant hass[581]:   File "/opt/assistant/lib64/python3.10/site-packages/zigpy/util.py", line 131, in retry
Feb 06 15:28:36 assistant hass[581]:     r = await func()
Feb 06 15:28:36 assistant hass[581]:   File "/opt/assistant/lib64/python3.10/site-packages/zigpy/device.py", line 210, in _initialize
Feb 06 15:28:36 assistant hass[581]:     status, _, endpoints = await self.zdo.Active_EP_req(
Feb 06 15:28:36 assistant hass[581]:   File "/opt/assistant/lib64/python3.10/site-packages/zigpy/util.py", line 131, in retry
Feb 06 15:28:36 assistant hass[581]:     r = await func()
Feb 06 15:28:36 assistant hass[581]:   File "/opt/assistant/lib64/python3.10/site-packages/zigpy/device.py", line 297, in request
Feb 06 15:28:36 assistant hass[581]:     await self._application.request(
Feb 06 15:28:36 assistant hass[581]:   File "/opt/assistant/lib64/python3.10/site-packages/zigpy/application.py", line 690, in request
Feb 06 15:28:36 assistant hass[581]:     await self.send_packet(
Feb 06 15:28:36 assistant hass[581]:   File "/opt/assistant/lib64/python3.10/site-packages/zigpy_znp/zigbee/application.py", line 1012, in send_packet
Feb 06 15:28:36 assistant hass[581]:     route_status = await self._znp.request(
Feb 06 15:28:36 assistant hass[581]: AttributeError: 'NoneType' object has no attribute 'request'
```

Latest ZHA latest ZHA Toolkit latest HASS.

**Comment by Rudd-O** [comment]
Oh wait, you should know this context: this was after reloading the ZHA integration.  If I restart HA, then it works fine.

**Comment by mdeweerd** [comment]
zha-toolkit depends on zha.  When zha/zigpy is not functional, some of the internal values are "None" and in the logs you share, zha/zigpy is failing.

I raised the importance of the notification message from zha_toolkit in case it does not initialize because ZHA is "missing" in b0898fd .  That will be in the next release.

**Comment by Rudd-O** [comment]
Thank you!
