### ISSUE TITLE
module 'zigpy_znp' has no attribute '__version__'

### ISSUE THREAD

**Issue by harishvelli** [mdeweerd/zha-toolkit#152]
Unable to run automation in new release of HASS (Home Assistant 2023.3.0)

Automation:
platform: time_pattern
minutes: /5
condition: []
action:
service: zha_toolkit.execute
data:
command: attr_read
ieee: 8c:f6:81:ff:fe:c4:2d:dc
cluster: 1029
attribute: 0
tries: 10
event_done: zha_done
service: zha_toolkit.execute
data:
command: attr_read
ieee: 8c:f6:81:ff:fe:c4:2d:dc
cluster: 1026
attribute: 0
tries: 10
event_done: zha_done
mode: single

Log/Error:

Logger: homeassistant.components.automation.manually_refresh_multi_sensors
Source: custom_components/zha_toolkit/utils.py:192
Integration: Automation (documentation, issues)
First occurred: 7:50:00 PM (4 occurrences)
Last logged: 7:50:38 PM

Manually Refresh Multi Sensors: Error executing script. Unexpected error for call_service at pos 1: module 'zigpy_znp' has no attribute '__version__'
While executing automation automation.manually_refresh_multi_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/zha_toolkit/__init__.py", line 699, in toolkit_service
    "zigpy_rf_version": u.get_radio_version(app),
  File "/config/custom_components/zha_toolkit/utils.py", line 192, in get_radio_version
    return zigpy_znp.__version__
AttributeError: module 'zigpy_znp' has no attribute '__version__'

**Comment by mdeweerd** [comment]
Thanks for reporting.

Can you check beta/pre-release v0.8.37 .
I do not upgrade to the first versions of the monthly updates, and I have not other means to check it myself at this time.

**Comment by mdeweerd** [comment]
Perfect, released!
