### ISSUE TITLE
Setup failed for custom integration zha_toolkit

### ISSUE THREAD

**Issue by claudegel** [mdeweerd/zha-toolkit#180]
Hi, since latest HA update I have this error message following HA restart:
...
File "/config/custom_components/zha_toolkit/utils.py", line 16, in <module>
    from zigpy import __version__ as zigpy_version
ImportError: cannot import name '__version__' from 'zigpy' (/usr/local/lib/python3.11/site-packages/zigpy/__init__.py)
I'm on:
Home Assistant 2023.7.2
Supervisor 2023.07.1
Operating System 10.3
Interface utilisateur : 20230705.1 - latest

**Comment by mdeweerd** [comment]
Same as #176 and fixed in v0.9.3

**Comment by rofo69** [comment]
Its not fully fixed in v0.9.3 which just got released, I am still seeing this in the logs:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/config/custom_components/zha_toolkit/__init__.py", line 704, in toolkit_service
    "zigpy_version": zigpy.__version__,
                     ^^^^^^^^^^^^^^^^^
AttributeError: module 'zigpy' has no attribute '__version__'


The fix looks pretty simple.

**Comment by mdeweerd** [comment]
I released v0.9.4 - hopefully that's the last one (except for ezsp_backup that is likely not used (a lot)).

I am currently waiting for my HA to restart because this change requires After updating zha_toolkit, a restart is needed after updating zha-toolkit for this fix as that part of the code is not reloaded automatically.
