### ISSUE TITLE
 "write" command returning error message.

### ISSUE THREAD

**Issue by johngalt991** [mdeweerd/zha-toolkit#232]
After updating to 2024.6, i am receiving an error message when trying to publish a messsage with "write" command.

LOG:

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: async_get() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 763, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 726, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zha_toolkit/__init__.py", line 725, in toolkit_service
    ieee = await u.get_ieee(app, zha_gw, ieee_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zha_toolkit/utils.py", line 286, in get_ieee
    else get_hass(listener).helpers.entity_registry.async_get(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: async_get() takes 1 positional argument but 2 were given

**Comment by CordoWEB** [comment]
The Pull Request https://github.com/mdeweerd/zha-toolkit/pull/231 seems to fix this issue.

**Comment by johngalt991** [comment]
> The Pull Request #231 seems to fix this issue.

Really sorry, but I don't know how to fix it based on your reply. Would you guide me more?

**Comment by mdeweerd** [comment]
#231 Has been integrated in the release so this should be fixed.
