### ISSUE TITLE
zha_toolkit fails with unknown error on any service call in HA 2024.7.2

### ISSUE THREAD

**Issue by MikeBP13** [mdeweerd/zha-toolkit#235]
Calling any service from zha_toolkit fails with unknown error.

HA Details:
```
Core 2024.7.2
Supervisor 2024.06.2
OS 12.4
Frontend 20240710.0
```

ZHA Toolkit:
`Version 1.1.10`

Relevant logs:
```
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:527
First occurred: 00:25:11 (4 occurrences)
Last logged: 11:00:38

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: async_get() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 527, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zha_toolkit/__init__.py", line 725, in toolkit_service
    ieee = await u.get_ieee(app, zha_gw, ieee_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zha_toolkit/utils.py", line 286, in get_ieee
    else get_hass(listener).helpers.entity_registry.async_get(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: async_get() takes 1 positional argument but 2 were given
```
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/zha_toolkit/utils.py:286
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 00:25:11 (4 occurrences)
Last logged: 11:00:38

[140248403275216] Error handling message: Unknown error (unknown_error) Mihai Petric from 192.168.100.174 (Mozilla/5.0 (Linux; Android 14; SM-G998B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36 Home Assistant/2024.6.1-12936 (Android 14; SM-G998B))
[140248462145376] Error handling message: Unknown error (unknown_error) Mihai Petric from 192.168.100.174 (Mozilla/5.0 (Linux; Android 14; SM-G998B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36 Home Assistant/2024.6.1-12936 (Android 14; SM-G998B))
[140248516618144] Error handling message: Unknown error (unknown_error) Mihai Petric from 127.0.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 793, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1770, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 465, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 529, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 559, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 527, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zha_toolkit/__init__.py", line 725, in toolkit_service
    ieee = await u.get_ieee(app, zha_gw, ieee_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zha_toolkit/utils.py", line 286, in get_ieee
    else get_hass(listener).helpers.entity_registry.async_get(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: async_get() takes 1 positional argument but 2 were given
```

**Comment by paulvt** [comment]
PR #231 fixed this for me!

**Comment by MikeBP13** [comment]
> PR #231 fixed this for me!

Ok. Can you point out how to use the proposed fix? I have no idea what to do... Thanks.

**Comment by paulvt** [comment]
If you don't know what to do with the diff/patch, I'd advise you not to try it manually. It is quite a surgical edit, sorry.
I hope the PR gets merged and released soon!

**Comment by mdeweerd** [comment]
I've integrated the fix in the official release now!
