### ISSUE TITLE
Setup failed with 2024.8.0b0

### ISSUE THREAD

**Issue by ChristophCaina** [mdeweerd/zha-toolkit#237]
with latest HA Beta (2024.8.0b0) I am getting the following error:

```
Logger: homeassistant.setup
Quelle: setup.py:333
Erstmals aufgetreten: 00:44:30 (1 Vorkommnisse)
Zuletzt protokolliert: 00:44:30

Setup failed for custom integration 'zha_toolkit': Unable to import component: No module named 'homeassistant.components.zha.core'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 333, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/zha_toolkit/__init__.py", line 7, in <module>
    from homeassistant.components.zha.core.gateway import ZHAGateway
ModuleNotFoundError: No module named 'homeassistant.components.zha.core'
```

**Comment by dualtronic** [comment]
ZHA was refactored and ZHA core removed or modified. Check this in the beta docs.  https://rc.home-assistant.io/blog/2024/07/31/release-20248/#zigbee-home-automation-zha-updates

**Comment by ChristophCaina** [comment]
That's what i want to do as soon as I am back home^^
