### ISSUE TITLE
Detected blocking call to open with args ... inside the event loop by custom integration 'zha_toolkit'

### ISSUE THREAD

**Issue by dhover** [mdeweerd/zha-toolkit#238]
'2024-08-01 14:49:53.028 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/custom_components/zha_toolkit/manifest.json',) inside the event loop by custom integration 'zha_toolkit' at custom_components/zha_toolkit/utils.py, line 88: with open(fname, encoding="utf_8") as infile: (offender: /config/custom_components/zha_toolkit/utils.py, line 88: with open(fname, encoding="utf_8") as infile:), please create a bug report at https://github.com/mdeweerd/zha-toolkit/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/setup.py", line 167, in async_setup_component
result = await _async_setup_component(hass, domain, config)
File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
result = await task
File "/config/custom_components/zha_toolkit/__init__.py", line 655, in async_setup
register_services(hass)
File "/config/custom_components/zha_toolkit/__init__.py", line 862, in register_services
LOADED_VERSION = u.getVersion()
File "/config/custom_components/zha_toolkit/utils.py", line 88, in getVersion
with open(fname, encoding="utf_8") as infile:'

**Comment by dhover** [comment]
HAOS version 2024.7.4
ZHA Toolkit version 1.11.1
