### ISSUE TITLE
Detected blocking call to open with args ('/config/custom_components/zha_toolkit/manifest.json',) inside the event loop

### ISSUE THREAD

**Issue by dhover** [mdeweerd/zha-toolkit#241]
```
2024-08-05 20:50:04.297 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/custom_components/zha_toolkit/manifest.json',) inside the event loop by custom integration 'zha_toolkit' at custom_components/zha_toolkit/utils.py, line 93: with open(fname, encoding="utf_8") as infile: (offender: /config/custom_components/zha_toolkit/utils.py, line 93: with open(fname, encoding="utf_8") as infile:), please create a bug report at https://github.com/mdeweerd/zha-toolkit/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/setup.py", line 167, in async_setup_component
result = await _async_setup_component(hass, domain, config)
File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
result = await task
File "/config/custom_components/zha_toolkit/__init__.py", line 660, in async_setup
await register_services(hass)
File "/config/custom_components/zha_toolkit/__init__.py", line 867, in register_services
LOADED_VERSION = await u.getVersion()
File "/config/custom_components/zha_toolkit/utils.py", line 93, in getVersion
with open(fname, encoding="utf_8") as infile:
```

**Comment by dhover** [comment]
After the latest update to v1.1.13 one blocking call is left.

**Comment by mdeweerd** [comment]
It's all wrapped in "async" already and still considered blocking - maybe the check is not ok.
Anyway, I made changes that hopefully fix it (not reproduced in my environment).

**Comment by dhover** [comment]
Error is still there with 1.1.14:
```
2024-08-06 19:29:55.606 WARNING (SyncWorker_2) [homeassistant.helpers.frame] Detected that custom integration 'zha_toolkit' calls hass.services.async_register from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassservicesasync_register at custom_components/zha_toolkit/__init__.py, line 853: hass.services.async_register(, please report it to the author of the 'zha_toolkit' custom integration
2024-08-06 19:29:55.607 ERROR (MainThread) [homeassistant.setup] Error during setup of component zha_toolkit
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
result = await task
^^^^^^^^^^
File "/config/custom_components/zha_toolkit/__init__.py", line 660, in async_setup
await hass.async_add_executor_job(register_services, hass)
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/zha_toolkit/__init__.py", line 853, in register_services
hass.services.async_register(
File "/usr/src/homeassistant/homeassistant/core.py", line 2515, in async_register
self._hass.verify_event_loop_thread("hass.services.async_register")
File "/usr/src/homeassistant/homeassistant/core.py", line 463, in verify_event_loop_thread
frame.report_non_thread_safe_operation(what)
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 225, in report_non_thread_safe_operation
report(
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
_report_integration(what, integration_frame, level, error_if_integration)
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
raise RuntimeError(
RuntimeError: Detected that custom integration 'zha_toolkit' calls hass.services.async_register from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassservicesasync_register at custom_components/zha_toolkit/__init__.py, line 853: hass.services.async_register(. Please report it to the author of the 'zha_toolkit' custom integration.
```
