### ISSUE TITLE
Changing SEA801 Thermostat setpoint - attr_write fails where GUI works fine

### ISSUE THREAD

**Issue by B-D-M-C** [mdeweerd/zha-toolkit#275]
Hi,

I am trying to set the setpoint temperature of my Saswell SEA801-Z01 Zigbee thermostat.
(Reason: the setpoint is not exposed to Home Assistant in a way that would allow for automations to control it)

Through the GUI's "Manage Zigbee device" I can select and read as well as write the correct parameter:
Reading works nicely:
![grafik](https://github.com/user-attachments/assets/f5a0fcd0-c73e-45c4-94d6-a70c8bf6e593)
Writing too (confirmed, as the value changes visibly on the device itself):
![grafik](https://github.com/user-attachments/assets/4d5a69de-d174-4e62-b8df-7cd543ca11d5)

Through the GUI "Developer tools" -> actions, I am using the zha_toolkit call to read the setpoint as follows:

```
action: zha_toolkit.execute
data:
  command: attr_read
  endpoint: 1
  cluster: 61184
  ieee: sensor.tze200_c88teujp_ts0601_32abcbfe_thermostat_hvac_action
  attribute: 615
```

with the following result:

```
zha_toolkit_version: v1.1.22
zigpy_version: 0.73.1
zigpy_rf_version: 0.42.5
ieee_org: sensor.tze200_c88teujp_ts0601_32abcbfe_thermostat_hvac_action
ieee: 5c:02:72:ff:fe:cd:ab:32
command: attr_read
command_data: null
start_time: "2024-12-23T10:44:21.863441+00:00"
errors: []
params:
  endpoint_id: 1
  cluster_id: 61184
  attr_id: 615
  dir: 0
  tries: 1
  expect_reply: true
  args: []
  kwargs: {}
  read_before_write: true
  read_after_write: true
attr_type: "0x23"
write_is_equal: false
result_read:
  - "615": 220
  - {}
success: true
```

But when I use the following to write a new value, I do get the same error no matter what:

```
action: zha_toolkit.execute
data:
  command: attr_write
  endpoint: 1
  cluster: 61184
  ieee: sensor.tze200_c88teujp_ts0601_32abcbfe_thermostat_hvac_action
  attribute: 615
  attr_val: "280"
  read_before_write: true
  read_after_write: true
```

with the following result:

```
zha_toolkit_version: v1.1.22
zigpy_version: 0.73.1
zigpy_rf_version: 0.42.5
ieee_org: sensor.tze200_c88teujp_ts0601_32abcbfe_thermostat_hvac_action
ieee: 5c:02:72:ff:fe:cd:ab:32
command: attr_write
command_data: null
start_time: "2024-12-23T10:50:32.023065+00:00"
errors: []
params:
  endpoint_id: 1
  cluster_id: 61184
  attr_id: 615
  attr_val: 280
  dir: 0
  tries: 1
  expect_reply: true
  args: []
  kwargs: {}
  read_before_write: true
  read_after_write: true
compare_val: 280
attr_type: "0x23"
write_is_equal: false
read_before:
  - "615": 220
  - {}
result_write:
  - - status: 134
      attrid: 615
result_read:
  - "615": 220
  - {}
success: false
```

As far as I understand, the error / status 134 means "unsupported attribute", but I do not change that attribute at all.
The write result even confirms the same attr_type = 0x23 (uint32) being used.
Manually setting it to the same type does not change the outcome. Setting a different type (33 == "0x21" == uint16) though generated an error message "type determined from read different from requested: 0x23 <> 0x267" 
--> why it shows the new set type to be 0x267 I do not know! (This is the value from the attr_id ... it's a bug in the logging?)

It works with the GUI, so what am I doing wrong here?
Or could this be some sort of bug?

Any help is much appreciated.

**Comment by mdeweerd** [comment]
It's a manufacturer cluster and you probably need to set the manufacturer id as well in this case.

FYI: The GUI is provided by ZHA and while zha-toolkit uses zha it "hacks" into the API to bypass some limitations or autmatic settings - in this case that is likely the manufacturer id you need to set manually.

At some point this might have been added automatically, or when the manf argument has a certain value.

**Comment by B-D-M-C** [comment]
Thanks for the quick response.

Its the same problem and result when I use the alternative non-manufacturer (?) parameter as follows:
   Cluster: ThermostatCluster (Endpoint id: 1, Id: 0x0201, Type: in)
   Attribute: occupied_heating_setpoint (id: 0x0012)
   attr_val: 2800

Do you know how I can find out the manf value I need to supply?

**Comment by mdeweerd** [comment]
You can do a device scan, an possibly find the details in the device information provided by ZHA (see 3 vertical dots).

(I am on a tight time schedule, so I can't check in detail).

**Comment by mdeweerd** [comment]
When you download the diagnostics for a device you'll fined "menufacturer_code" for devices in the json file:

```json
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 38757,
    "manufacturer": "_TZ3000_gbm10jnj",
    "model": "TS0043",
    "name": "_TZ3000_gbm10jnj TS0043",
    "quirk_applied": true,
    "quirk_class": "zhaquirks.tuya.ts0043.TuyaSmartRemote0043TO",
    "quirk_id": null,
    "manufacturer_code": 4098,
```

When you use zha-toolkit to perform a device scan, you'll also find the manufacturer code:
```json
{
  "ieee": "f4:b3:b1:ff:fe:dd:77:28",
  "nwk": "0x7d7b",
  "model": "SIN-4-FP-21",
  "manufacturer": "NodOn",
  "manufacturer_id": "0x4747",
```

You can call the device scan from developer tools > services.  The result will be shown in the UI and you can find a fie in the scans directory under config.

**Comment by MattWestb** [comment]
@mdeweerd The clusters (can being all or only some) on tuya MCU (or mixed real Zigbee and MCU) devices is virtual then all (MCU) commands is piped thru tuya cluster thru the quirks that ZHA have loaded for it to the MCU. Shall working OK but its little more between the normal standard Zigbee stuff and the tuya MCU. 
And yes some of the devices need manufacture code in the frame (in the Zigbee network layer) but it shall being done of the quirk as can see in the screen shuts its not being used from ZHA GUI but it was working OK. If trying going around the quirk its need diving very deep in the rabbit hole for fixing all tuya abnormal things they have implemented.

**Comment by B-D-M-C** [comment]
Thanks for that!
But no luck, unfortunately.

Here some of the diagnostics: 
```
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 14733,
    "manufacturer": "_TZE200_c88teujp",
    "model": "TS0601",
    "name": "_TZE200_c88teujp TS0601",
    "quirk_applied": true,
    "quirk_class": "zhaquirks.tuya.ts0601_trv_sas.Thermostat_TZE200_c88teujp",
    "quirk_id": null,
    "manufacturer_code": 4098,
    "power_source": "Battery or Unknown",
    ...
```

so I tried the manufacturer ID of 4098 with both the "ManufacturerThermostatCluster" and the "ThermostatCluster" but got the exact same result as before.
I even tried another few IDs but even then I still got the exact same result.

I am out of ideas. What else could it be?

**Comment by mdeweerd** [comment]
I would check if there is actual information about the attribute that can be determined from the device scan that zha-toolkit can do.  The ZHA GUI indicates it is writable, but is it?

Further, as the request through the ZHA GUI function is functionnal, you could also increase logging in order to see the actually zigbee request that is sent to the device.

On could also examine the quirk code to see what is defined/implemented there.

One other means I have is to sniff the packets that we can observe in the air, but most of the time the information in the logs are ok.

Possibly - as this is tuya - the cluster does not need the manufacturer code and you could see what happens if it actually set to 0.

**Comment by B-D-M-C** [comment]
Ok, got more infos now:
(And sorry for delay in response)

The ZHA GUI is definitely writing values successfully to the device (value is shown on the thermostats display and that changes immediately after writing that attribute (either attribute))

ZHA GUI logging does not reveal much unfortunately...
Reading the attribute:
`[36m2024-12-25 17:00:04.260 DEBUG (MainThread) [homeassistant.components.zha.websocket_api] Read attribute for: cluster_id: [513] cluster_type: [in] endpoint_id: [1] attribute: [18] manufacturer: [None] response: [2200] failure: [{}]`

Writing the attribute:
`[36m2024-12-25 17:00:09.259 DEBUG (MainThread) [homeassistant.components.zha.websocket_api] Set attribute for: cluster_id: [513] cluster_type: [in] endpoint_id: [1] attribute: [18] value: [2400] manufacturer: [None] response: [[[WriteAttributesStatusRecord(status=<Status.SUCCESS: 0>)]]]`

Scan / device info confirm that the attribute type is 41 == 0x29 == int16s
```
             "0x0012": {
                "attribute": "ZCLAttributeDef(id=0x0012, name='occupied_heating_setpoint', type=<class 'zigpy.types.basic.int16s'>, zcl_type=<DataTypeId.int16: 41>, access=<ZCLAttributeAccess.Read|Write|Scene: 19>, mandatory=False, is_manufacturer_specific=False)",
```

In the log I can see that the write call fails as follows:
```
[36m2024-12-25 17:28:13.750 DEBUG (MainThread) [custom_components.zha_toolkit] running default command: <ServiceCall zha_toolkit.execute (c:01JFZABDYY9JJQ3RSCGRVVABQC): command=attr_write, ieee=sensor.tze200_c88teujp_ts0601_32abcbfe_thermostat_hvac_action, endpoint=1, cluster=513, attribute=18, attr_val=2900, read_after_write=True, read_before_write=True>
[36m2024-12-25 17:28:13.757 DEBUG (ImportExecutor_0) [custom_components.zha_toolkit.default] Trying to import custom_components.zha_toolkit.zcl_attr to call attr_write
[36m2024-12-25 17:28:13.764 DEBUG (MainThread) [custom_components.zha_toolkit.utils] IEEE for get_device: 5c:02:72:ff:fe:cd:ab:32 5c:02:72:ff:fe:cd:ab:32
[36m2024-12-25 17:28:13.765 DEBUG (MainThread) [custom_components.zha_toolkit.zcl_attr] Request attr read [18]
[36m2024-12-25 17:28:13.766 DEBUG (MainThread) [custom_components.zha_toolkit.zcl_attr] Reading attr result (attrs, status): ({18: 2550}, {})
[36m2024-12-25 17:28:13.766 DEBUG (MainThread) [custom_components.zha_toolkit.zcl_attr] Type determined from read: 0x29
[36m2024-12-25 17:28:13.767 DEBUG (MainThread) [custom_components.zha_toolkit.zcl_attr] Request attr write [Attribute(attrid=0x0012, value=TypeValue(type=int16s, value=2900))]
[36m2024-12-25 17:28:17.305 DEBUG (MainThread) [custom_components.zha_toolkit.zcl_attr] Write attr status: Write_Attributes_rsp(status_records=[WriteAttributesStatusRecord(status=<Status.UNSUPPORTED_ATTRIBUTE: 134>, attrid=0x0012)])
```

And if I manually set the type with "attr_type: 41" I get the exact same result:
```
[36m2024-12-25 17:45:42.912 DEBUG (MainThread) [custom_components.zha_toolkit] running default command: <ServiceCall zha_toolkit.execute (c:01JFZBBEHZY1X6YPT9QFH63M61): command=attr_write, ieee=sensor.tze200_c88teujp_ts0601_32abcbfe_thermostat_hvac_action, endpoint=1, cluster=513, attribute=18, attr_type=41, attr_val=2900, read_after_write=True, read_before_write=True>
[36m2024-12-25 17:45:42.921 DEBUG (ImportExecutor_0) [custom_components.zha_toolkit.default] Trying to import custom_components.zha_toolkit.zcl_attr to call attr_write
[36m2024-12-25 17:45:42.927 DEBUG (MainThread) [custom_components.zha_toolkit.utils] IEEE for get_device: 5c:02:72:ff:fe:cd:ab:32 5c:02:72:ff:fe:cd:ab:32
[36m2024-12-25 17:45:42.928 DEBUG (MainThread) [custom_components.zha_toolkit.zcl_attr] Request attr read [18]
[36m2024-12-25 17:45:42.929 DEBUG (MainThread) [custom_components.zha_toolkit.zcl_attr] Reading attr result (attrs, status): ({18: 2550}, {})
[36m2024-12-25 17:45:42.930 DEBUG (MainThread) [custom_components.zha_toolkit.zcl_attr] Type determined from read: 0x29
[36m2024-12-25 17:45:42.930 DEBUG (MainThread) [custom_components.zha_toolkit.zcl_attr] Request attr write [Attribute(attrid=0x0012, value=TypeValue(type=int16s, value=2900))]
[36m2024-12-25 17:45:43.774 DEBUG (MainThread) [custom_components.zha_toolkit.zcl_attr] Write attr status: Write_Attributes_rsp(status_records=[WriteAttributesStatusRecord(status=<Status.UNSUPPORTED_ATTRIBUTE: 134>, attrid=0x0012)])
```

I was not able to look at the toolkit code yet: why is that error "UNSUPPORTED_ATTRIBUTE: 134" generated?

Thanks, and happy new year! :)

**Comment by mdeweerd** [comment]
Hi, best wishes for 2025 too!  I've been "away" from HA coding for longer than that;

UNSUPPORTED_ATTRIBUTE (134) corresponds to the reply from the device for the command that it received.

From the scan, and other indicators I can now be sure that the manufacturer code does not need to be set.
We can also see that the zha_toolkit can read the value (which it does by default before writing), but that something goes wrong when writing it.

If you set the logging for zigpy, we will get more information about what is sent:

```yaml
service: logger.set_level
data:
  custom_components.zha_toolkit: debug
  zigpy.zcl: debug
```

We can then find information like this in the logs even for requests sent through zha-toolkit - and hopefully we get extra information.
```plaintext
[zigpy.zcl] [0xF1FF:1:0x0201] Sending request header: ZCLHeader(frame_control=FrameControl<0x04>(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=True, direction=<Direction.Client_to_Server: 0>, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True), manufacturer=4678, tsn=16, command_id=<GeneralCommand.Write_Attributes: 2>, *direction=<Direction.Client_to_Server: 0>)
[zigpy.zcl] [0xF1FF:1:0x0201] Sending request: Write_Attributes(attributes=[Attribute(attrid=0x4015, value=TypeValue(type=int16s, value=1913))])
[zigpy.zcl] [0xF1FF:1:0x0201] Decoded ZCL frame: DanfossThermostatCluster:Write_Attributes_rsp(status_records=[WriteAttributesStatusRecord(status=<Status.SUCCESS: 0>)])
```

**Comment by B-D-M-C** [comment]
Ok, thanks!

Set debug level and ran GUI command:

```
2025-01-02 17:51:04.059 DEBUG (MainThread) [zigpy.zcl] [0x398D:1:0xef00] Sending request header: ZCLHeader(frame_control=FrameControl<0x05>(frame_type=<FrameType.CLUSTER_COMMAND: 1>, is_manufacturer_specific=True, direction=<Direction.Client_to_Server: 0>, disable_default_response=0, reserved=0, *is_cluster=True, *is_general=False), manufacturer=4098, tsn=58, command_id=0, *direction=<Direction.Client_to_Server: 0>)
2025-01-02 17:51:04.062 DEBUG (MainThread) [zigpy.zcl] [0x398D:1:0xef00] Sending request: set_data(param=Command(status=0, tsn=58, command_id=615, function=0, data=290))
2025-01-02 17:51:04.558 DEBUG (MainThread) [zigpy.zcl] [0x398D:1:0xef00] Received ZCL frame: b'\x0c\x02\x10:\x0b\x00\x00'
2025-01-02 17:51:04.561 DEBUG (MainThread) [zigpy.zcl] [0x398D:1:0xef00] Decoded ZCL frame header: ZCLHeader(frame_control=FrameControl<0x0C>(frame_type=<FrameType.GLOBAL_COMMAND: 0>, is_manufacturer_specific=True, direction=<Direction.Server_to_Client: 1>, disable_default_response=0, reserved=0, *is_cluster=False, *is_general=True), manufacturer=4098, tsn=58, command_id=11, *direction=<Direction.Server_to_Client: 1>)
2025-01-02 17:51:04.563 DEBUG (MainThread) [zigpy.zcl] [0x398D:1:0xef00] Decoded ZCL frame: ManufacturerThermostatCluster:Default_Response(command_id=0, status=<Status.SUCCESS: 0>)
2025-01-02 17:51:04.566 DEBUG (MainThread) [zigpy.zcl] [0x398D:1:0xef00] Received command 0x0B (TSN 58): Default_Response(command_id=0, status=<Status.SUCCESS: 0>)
2025-01-02 17:51:04.571 DEBUG (MainThread) [homeassistant.components.zha.websocket_api] Set attribute for: cluster_id: [513] cluster_type: [in] endpoint_id: [1] attribute: [18] value: [2900] manufacturer: [None] response: [[[WriteAttributesStatusRecord(status=<Status.SUCCESS: 0>)]]]
```

This looks quite different here to what I thought it should be.
Looks like the GUI is doing more / differently than I would have expected:
Things I do recognise from the log:
- "set_data" is used in some way, not the "attr_write" I've seen Toolkit use for (unsuccessfully) wiriting the attribute value.
- The command_id=615 is the SASWELL_HEATING_SETPOINT_ATTR = 0x0267 (according to the quirk from that device: [Link](https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/tuya/ts0601_trv_sas.py#L37))
- The GUI provided data is being converted from centi-degree (2900) to deci-degree (290) => 29°C

But unfortunately I still do not understand how I can use this new info and the Toolkit to write that data to the device.
@mdeweerd Any ideas?

**Comment by mdeweerd** [comment]
Hi

I kind of suspected this, but proff was needed.

Inspection of
https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/tuya/ts0601_trv_sas.py

shows that it relies on

https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/tuya/__init__.py#L456-L479

which converts an attribute write into a zigbee command (not a zigbee attribute write).

So in order to do your "attribute write", you need to performa a `zcl_cmd` and as you discovered you need to indicate your value in decidegrees.

Converting what we see in the logs: `(status=0, tsn=58, command_id=615, function=0, data=290)`


```yaml
service: zha_toolkit.zcl_cmd
data:
  ieee: <the_reference_to_your device: entity_id, device_id or ieee address>
  cmd: 615
  cluster: 513
  endpoint: 1
  # Optional: direction (0=to in_cluster (default), 1=to out_cluster),
  dir: 0
  # I think this is needed as the command is manufacturer specific and the id is given
  manf: 4098
  # Optional: tries - default : 1
  # tries: 1
  # Optional (only add when the command requires it): arguments (default=empty)
  # Needs some experimenting: I am not sure the command is "known", so you may need to set the bytes for each argument.
  # I believe each group is an argument, maybe you need to provide the argument type.
  # I have not worked on/tested commands with unknown arguments - ZHA-toolkit may need an update for this.
  args: [[0x02,0x10]]  # or [[0x0c,0x02,0x10]]
```

**Comment by mdeweerd** [comment]
There is also the possibility that if you used `zha.set_zigbee_cluster_attribute` you go through the usual zha layers - including the device quirk.

**Comment by B-D-M-C** [comment]
Oh, exciting. Getting closer...

I tried it but unfortunately I got an error as the command_id is larger than an uint8:
In detail:

```
2025-01-02 21:06:38.286 ERROR (MainThread) [custom_components.zha_toolkit] Exception 'Failed to convert command_id=615 from type <class 'int'> to <class 'zigpy.types.basic.uint8_t'>' for service call with data '{'zha_toolkit_version': 'v1.1.22', 'zigpy_version': '0.73.1', 'zigpy_rf_version': '0.42.5', 'ieee_org': 'sensor.tze200_c88teujp_ts0601_32abcbfe_thermostat_hvac_action', 'ieee': '5c:02:72:ff:fe:cd:ab:32', 'command': 'zcl_cmd', 'command_data': None, 'start_time': '2025-01-02T20:06:38.273332+00:00', 'errors': ['ValueError("Failed to convert command_id=615 from type <class \'int\'> to <class \'zigpy.types.basic.uint8_t\'>")'], 'params': {'cmd_id': 615, 'endpoint_id': 1, 'cluster_id': 513, 'dir': 0, 'manf': 4098, 'tries': 1, 'expect_reply': True, 'args': [[2, 16]], 'kwargs': {}, 'read_before_write': True, 'read_after_write': True}, 'success': False}'
2025-01-02 21:06:38.286 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Failed to convert command_id=615 from type <class 'int'> to <class 'zigpy.types.basic.uint8_t'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/zigpy/types/struct.py", line 50, in _convert_type
    return field_type(value)
  File "/usr/local/lib/python3.13/site-packages/zigpy/types/basic.py", line 100, in __new__
    raise ValueError(
    ...<2 lines>...
    )
ValueError: 615 is not an unsigned 8 bit integer
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/zha_toolkit/__init__.py", line 833, in toolkit_service
    raise handler_exception
  File "/config/custom_components/zha_toolkit/__init__.py", line 785, in toolkit_service
    handler_result = await handler(
                     ^^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "/config/custom_components/zha_toolkit/__init__.py", line 899, in command_handler_default
    return await default.default(
           ^^^^^^^^^^^^^^^^^^^^^^
        app, listener, ieee, cmd, data, service, params, event_data
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/zha_toolkit/default.py", line 51, in default
    await handler(app, listener, ieee, cmd, data, service, params, event_data)
  File "/config/custom_components/zha_toolkit/zcl_cmd.py", line 159, in zcl_cmd
    raise caught_e
  File "/config/custom_components/zha_toolkit/zcl_cmd.py", line 117, in zcl_cmd
    event_data["cmd_reply"] = await u.retry_wrapper(
                              ^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/config/custom_components/zha_toolkit/utils.py", line 1096, in retry_wrapper
    return await retry(
           ^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/config/custom_components/zha_toolkit/utils.py", line 1077, in retry
    return await func()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/zhaquirks/tuya/__init__.py", line 763, in command
    ].schema(
      ~~~~~~^
        command_id=command_id, status=foundation.Status.UNSUP_CLUSTER_COMMAND
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/zigpy/types/struct.py", line 118, in __new__
    setattr(instance, name, field._convert_type(value, struct=instance))
                            ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/zigpy/types/struct.py", line 52, in _convert_type
    raise ValueError(
    ...<2 lines>...
    ) from e
ValueError: Failed to convert command_id=615 from type <class 'int'> to <class 'zigpy.types.basic.uint8_t'>

```

**Comment by mdeweerd** [comment]
I think that there is misleading information, the command id seems to be '0' (command_id=0).  
Possibly this means "set_data" as a manufacturer command for a Tuya device which in turn takes the argument 617 .  So you need to add 617 (as a group bytes and probably type) to the command as well.

**Comment by mdeweerd** [comment]
Here you can see that set_data is a Tuya command:

https://github.com/zigpy/zha-device-handlers/edit/dev/zhaquirks/tuya/__init__.py#L512-L527

**Comment by mdeweerd** [comment]
Here you have the structure for the TuyaCommand data (=arguments):

https://github.com/zigpy/zha-device-handlers/edit/dev/zhaquirks/tuya/__init__.py#L325-L331

**Comment by B-D-M-C** [comment]
> There is also the possibility that if you used `zha.set_zigbee_cluster_attribute` you go through the usual zha layers - including the device quirk.

Yesss, so this does indeed work nicely:

```
alias: set_temperature_at_thermostat
sequence:
  - data:
      ieee: 5c:02:72:ff:fe:cd:ab:32
      endpoint_id: 1
      cluster_id: 513
      attribute: 18
      cluster_type: in
      value: 2900
      manufacturer: "4098"
    action: zha.set_zigbee_cluster_attribute
```

**Comment by mdeweerd** [comment]
Ok, so you can go with that ;-).

**Comment by B-D-M-C** [comment]
I have not fully understood the way of doing it with a zigbee command via Toolkit yet.
I might come back to it. Would love to understand it a bit better... :)

But for now I will try it with the zha.set_zigbee_cluster_attribute.

I will add a more details here in the next few days once I figured out how to use it in my automations, controlling the temperature "dynamically". May be useful to some...

Thank you so much @mdeweerd !!

**Comment by B-D-M-C** [comment]
I wrote up how I used the zha.set_zigbee_cluster_attribute to control the setpoint of the thermostats in my automations.
See here: https://community.home-assistant.io/t/easy-way-of-setting-temperature-setpoint-for-ts0601-sea801-thermostats-with-zha-in-automations/821498
