### ISSUE TITLE
Unknown error while running service: zha_toolkit.backup

### ISSUE THREAD

**Issue by JoryHogeveen** [mdeweerd/zha-toolkit#39]
Same error occurs if I try the same with zha_toolkit.execute (command: backup)

```Exception: Radio type RadioType.UNKNOWN not supported for backup
2022-03-08 15:54:36 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281473033533136] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 552, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1243, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 349, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 367, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 570, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/zha_toolkit/__init__.py", line 670, in toolkit_service
    raise handler_exception
  File "/config/custom_components/zha_toolkit/__init__.py", line 634, in toolkit_service
    await handler(
  File "/config/custom_components/zha_toolkit/__init__.py", line 719, in command_handler_default
    await default.default(
  File "/config/custom_components/zha_toolkit/default.py", line 33, in default
    await handler(app, listener, ieee, cmd, data, service, params, event_data)
  File "/config/custom_components/zha_toolkit/misc.py", line 71, in backup
    raise Exception(
Exception: Radio type RadioType.UNKNOWN not supported for backup
```

**Comment by mdeweerd** [comment]
`
Exception: Radio type RadioType.UNKNOWN not supported for backup
`
What radio are you using - it probably isn't a TI/ZNP type or EZSP/Bellows type.

While the code can be updated to detect the radio type (rather than spitting out unknown), only the ZNP and EZSP radios had backup methods - work is ongoing for the other radios.

**Comment by JoryHogeveen** [comment]
Hi @mdeweerd 
I honestly have no idea where to even look for in terms of what radio I am using.
My first guess would be the controller? If so, it's a Conbee II.

**Comment by mdeweerd** [comment]
Conbee II is using zigpy_deconz and doesn't have backup at the moment.

I've added radio recognition to the development branch, I hope it will work as I do not have anything to test it with.

**Comment by JoryHogeveen** [comment]
Awesome, I'll test as soon as the new version is available in HACS. Thank you!

**Comment by JoryHogeveen** [comment]
@mdeweerd 
Running 0.8.0 but backup isn't working yet unfortunately :(

**Comment by mdeweerd** [comment]
I will add backup for Deconz when it is availalble, but now the radio type is identified - it no longer indicates "UNKNOWN" in the message.
