### ISSUE TITLE
can not resart homeassistant after install zha_toolkit

### ISSUE THREAD

**Issue by Aubrey-207** [mdeweerd/zha-toolkit#47]
Error info:
   module 'homeassistant.helpers.config_validation' has no attribute 'entity_id_or_uuid'
Details:
  Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 585, in async_handle_core_service
    errors = await conf_util.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/config.py", line 938, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 139, in async_check_ha_config_file
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 522, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/zha_toolkit/__init__.py", line 38, in <module>
    cv.entity_id_or_uuid, t.EUI64.convert
AttributeError: module 'homeassistant.helpers.config_validation' has no attribute 'entity_id_or_uuid'

**Comment by mdeweerd** [comment]
Très surprenant, la dernière version comporte toujours ce validateur:

https://github.com/home-assistant/core/blob/2022.3.5/homeassistant/helpers/config_validation.py#L281-L287

Vous utilisez quelle version de HA?
visiblement c'était ajouté il y a 4 mois.

Soit j'incrémente la version minimum de HA dans le manifest, soit je modifie la validation, soit il y a autre chose à corriger.

**Comment by mdeweerd** [comment]
Apparently this was made available in HA 2021.12.1 (or slightly earlier) but not in 2021.11.0 .

**Comment by mdeweerd** [comment]
@Aubrey-207 Can you provide some feedback?  Otherwise I will have to close this.
