### ISSUE TITLE
attr_type value for attr_write

### ISSUE THREAD

**Issue by shawnbarton** [mdeweerd/zha-toolkit#7]
I am a little confused what my attr_type value should be when I want to do an attr_write. I need to write a uint16. Could you please clarify?

I have found a list of the Zigbee data types [here](https://mmbnetworks.atlassian.net/wiki/spaces/SPRC2/pages/111321476/Zigbee+Specification+References), which indicates my attr_type should probably be 0x21.

`attr_val: 0x2710`
`attr_type: 0x21`

`2022-02-08 15:10:38 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1706284752] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 534, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1253, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 354, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 372, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 575, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/zha_toolkit/__init__.py", line 415, in toolkit_service
    raise handler_exception
  File "/config/custom_components/zha_toolkit/__init__.py", line 379, in toolkit_service
    await handler(
  File "/config/custom_components/zha_toolkit/zcl_attr.py", line 164, in attr_write
    attr_val = f.TypeValue(attr_type, t.FixedIntType(compare_val))
  File "/usr/local/lib/python3.9/site-packages/zigpy/types/basic.py", line 57, in __new__
    raise TypeError(f"{cls} is abstract and cannot be created")
TypeError: <class 'zigpy.types.basic.FixedIntType'> is abstract and cannot be created`

This occurs even if I pass `attr_val: 10000` (both quoted and not)
Thanks!

**Comment by mdeweerd** [comment]
You are correct, you need a 0x21.

The error occurs because the 0x21 was not explicitly implemented and the generic method does not work.  I added types in 0.7.8.

In the toolkit I am not making assumptions about the types, and I haven't looked where they can be found.

Methods to identify the attribute type are:
- Examine the documentation/ZCL specification.
- Use scan_device to get the attribute type.  Currently the numeric value isn't mentioned, I add it in 0.7.9.
- Read the attribute first, but that's not reported through the zigpy API, only sniffable.

**Comment by shawnbarton** [comment]
Thank you!

**Comment by mdeweerd** [comment]
The attribute will no longer be required in version >=0.7.12 and the attribute can be provided as a string (name defined in zigpy).
I'll be using this a bit before making a new release.
