### ISSUE TITLE
AttributeError reading __name__ from a string

### ISSUE THREAD

**Issue by Rudd-O** [mdeweerd/zha-toolkit#80]
```
Aug 17 07:07:49 assistant hass[40674]: 2022-08-17 07:07:49.512 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall zha_toolkit.scan_device (c:01GAN9V6CQHGW1ANFBFEZSC0QF): ieee=00:17:88:01:0c:c3:a8:43, event_done=zha_done>
Aug 17 07:07:49 assistant hass[40674]: Traceback (most recent call last):
Aug 17 07:07:49 assistant hass[40674]:   File "/opt/assistant/lib64/python3.10/site-packages/homeassistant/core.py", line 1731, in catch_exceptions
Aug 17 07:07:49 assistant hass[40674]:     await coro_or_task
Aug 17 07:07:49 assistant hass[40674]:   File "/opt/assistant/lib64/python3.10/site-packages/homeassistant/core.py", line 1750, in _execute_service
Aug 17 07:07:49 assistant hass[40674]:     await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
Aug 17 07:07:49 assistant hass[40674]:   File "/var/lib/assistant/custom_components/zha_toolkit/__init__.py", line 698, in toolkit_service
Aug 17 07:07:49 assistant hass[40674]:     raise handler_exception
Aug 17 07:07:49 assistant hass[40674]:   File "/var/lib/assistant/custom_components/zha_toolkit/__init__.py", line 662, in toolkit_service
Aug 17 07:07:49 assistant hass[40674]:     await handler(
Aug 17 07:07:49 assistant hass[40674]:   File "/var/lib/assistant/custom_components/zha_toolkit/__init__.py", line 747, in command_handler_default
Aug 17 07:07:49 assistant hass[40674]:     await default.default(
Aug 17 07:07:49 assistant hass[40674]:   File "/var/lib/assistant/custom_components/zha_toolkit/default.py", line 33, in default
Aug 17 07:07:49 assistant hass[40674]:     await handler(app, listener, ieee, cmd, data, service, params, event_data)
Aug 17 07:07:49 assistant hass[40674]:   File "/var/lib/assistant/custom_components/zha_toolkit/scan_device.py", line 398, in scan_device
Aug 17 07:07:49 assistant hass[40674]:     scan = await scan_results(device, endpoints, manufacturer=manf)
Aug 17 07:07:49 assistant hass[40674]:   File "/var/lib/assistant/custom_components/zha_toolkit/scan_device.py", line 81, in scan_results
Aug 17 07:07:49 assistant hass[40674]:     endpoint.update(await scan_endpoint(ep, manufacturer))
Aug 17 07:07:49 assistant hass[40674]:   File "/var/lib/assistant/custom_components/zha_toolkit/scan_device.py", line 120, in scan_endpoint
Aug 17 07:07:49 assistant hass[40674]:     clusters[key] = await scan_cluster(
Aug 17 07:07:49 assistant hass[40674]:   File "/var/lib/assistant/custom_components/zha_toolkit/scan_device.py", line 154, in scan_cluster
Aug 17 07:07:49 assistant hass[40674]:     cmds_gen: await discover_commands_generated(cluster, is_server),
Aug 17 07:07:49 assistant hass[40674]:   File "/var/lib/assistant/custom_components/zha_toolkit/scan_device.py", line 360, in discover_commands_generated
Aug 17 07:07:49 assistant hass[40674]:     cmd_args = [arg.__name__ for arg in cmd_args]
Aug 17 07:07:49 assistant hass[40674]:   File "/var/lib/assistant/custom_components/zha_toolkit/scan_device.py", line 360, in <listcomp>
Aug 17 07:07:49 assistant hass[40674]:     cmd_args = [arg.__name__ for arg in cmd_args]
Aug 17 07:07:49 assistant hass[40674]: AttributeError: 'str' object has no attribute '__name__'
```

from the latest stable zha_toolkit published via HACS.

**Comment by mdeweerd** [comment]
Was kind of similar to one of the issues in #52.

In #52 it was a TypeError, so the TypeError was catched and acted upon.

Now it's an AttributeError.  Possibly due to the evolving python interpreter.
So now the code also acts on the AttributeError.
