### ISSUE TITLE
Can get any of the zha_toolkit services to run'

### ISSUE THREAD

**Issue by tunerooster** [mdeweerd/zha-toolkit#99]
In Developer Tools/Services I run:
```
service: zha_toolkit.backup
data:
  command_data: _initial
```
In the log I get:
```
2022-10-26 20:28:05.924 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2022-10-26 20:28:05.925 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2022-10-26 20:28:05.927 INFO (MainThread) [custom_components.zha_toolkit] Running ZHA Toolkit service: <ServiceCall zha_toolkit.backup (c:01GGBM99N3V4NGXHAEK1K16X24): command_data=_initial>
2022-10-26 20:28:05.964 DEBUG (MainThread) [custom_components.zha_toolkit] module is <module 'custom_components.zha_toolkit' from '/home/homeassistant/.homeassistant/custom_components/zha_toolkit/__init__.py'>
2022-10-26 20:28:05.972 DEBUG (MainThread) [custom_components.zha_toolkit.utils] Parameters '{'command_data': '_initial'}'
2022-10-26 20:28:05.972 DEBUG (MainThread) [custom_components.zha_toolkit.utils] Final manf 'None'
2022-10-26 20:28:05.973 DEBUG (MainThread) [custom_components.zha_toolkit] Default handler for backup
2022-10-26 20:28:05.973 DEBUG (MainThread) [custom_components.zha_toolkit] Handler: <function command_handler_default at 0x7fced3ade3a0>
2022-10-26 20:28:05.973 DEBUG (MainThread) [custom_components.zha_toolkit] running default command: <ServiceCall zha_toolkit.backup (c:01GGBM99N3V4NGXHAEK1K16X24): command_data=_initial>
2022-10-26 20:28:05.976 DEBUG (MainThread) [custom_components.zha_toolkit.default] Trying to import custom_components.zha_toolkit.misc to call backup
2022-10-26 20:28:06.027 DEBUG (MainThread) [custom_components.zha_toolkit] event_data {'zha_toolkit_version': 'v0.8.20', 'zigpy_version': '0.51.3', 'zigpy_rf_version': '0.34.2', 'ieee_org': None, 'ieee': 'None', 'command': 'backup', 'command_data': '_initial', 'start_time': '2022-10-27T02:28:05.973004+00:00', 'errors': ['AssertionError()'], 'params': {'dir': 0, 'tries': 1, 'expect_reply': True, 'args': [], 'read_before_write': True, 'read_after_write': True}, 'success': False}
2022-10-26 20:28:06.028 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 
Traceback (most recent call last):
  File "/home/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/home/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/home/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/home/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/home/homeassistant/.homeassistant/custom_components/zha_toolkit/__init__.py", line 717, in toolkit_service
    raise handler_exception
  File "/home/homeassistant/.homeassistant/custom_components/zha_toolkit/__init__.py", line 681, in toolkit_service
    await handler(
  File "/home/homeassistant/.homeassistant/custom_components/zha_toolkit/__init__.py", line 766, in command_handler_default
    await default.default(
  File "/home/homeassistant/.homeassistant/custom_components/zha_toolkit/default.py", line 33, in default
    await handler(app, listener, ieee, cmd, data, service, params, event_data)
  File "/home/homeassistant/.homeassistant/custom_components/zha_toolkit/misc.py", line 60, in backup
    await ezsp.ezsp_backup(
  File "/home/homeassistant/.homeassistant/custom_components/zha_toolkit/ezsp.py", line 328, in ezsp_backup
    result = await bellows_backup._backup(app._ezsp)
  File "/home/homeassistant/homeassistant/lib/python3.9/site-packages/bellows/cli/backup.py", line 88, in _backup
    assert status == t.EmberStatus.SUCCESS
AssertionError
2022-10-26 20:28:06.036 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140526569325616] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/home/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/home/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/components/websocket_api/commands.py", line 648, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/home/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/home/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/home/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/home/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/home/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/home/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/home/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/home/homeassistant/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/home/homeassistant/.homeassistant/custom_components/zha_toolkit/__init__.py", line 717, in toolkit_service
    raise handler_exception
  File "/home/homeassistant/.homeassistant/custom_components/zha_toolkit/__init__.py", line 681, in toolkit_service
    await handler(
  File "/home/homeassistant/.homeassistant/custom_components/zha_toolkit/__init__.py", line 766, in command_handler_default
    await default.default(
  File "/home/homeassistant/.homeassistant/custom_components/zha_toolkit/default.py", line 33, in default
    await handler(app, listener, ieee, cmd, data, service, params, event_data)
  File "/home/homeassistant/.homeassistant/custom_components/zha_toolkit/misc.py", line 60, in backup
    await ezsp.ezsp_backup(
  File "/home/homeassistant/.homeassistant/custom_components/zha_toolkit/ezsp.py", line 328, in ezsp_backup
    result = await bellows_backup._backup(app._ezsp)
  File "/home/homeassistant/homeassistant/lib/python3.9/site-packages/bellows/cli/backup.py", line 88, in _backup
    assert status == t.EmberStatus.SUCCESS
AssertionError
```
Same thing happens for all zha_toolkit services.

I am running core Home Assistant 2022.10.5 (Frontend 20221010.0) and zha_toolkit 0.8.20

What can I do to fix it, or find the problem?

Thanks!

**Comment by mdeweerd** [comment]
The core issue is this:

```
    result = await bellows_backup._backup(app._ezsp)
  File "/home/homeassistant/homeassistant/lib/python3.9/site-packages/bellows/cli/backup.py", line 88, in _backup
    assert status == t.EmberStatus.SUCCESS
```

So the questions are:
- Is `await bellows_backup._backup(app._ezsp)` (still) the proper way to start a backup.
- or, what is causing `assert status == t.EmberStatus.SUCCESS` to fail (i.e., why is `bellows_backup._backup` resulting in a failure). 

Maybe some logging can be done with regards to why the backup process is failing.

Howver 2022.10.5 has integrated ZHA backups - I haven't verified how that works, but I know you can download a backup using the ui.

**Comment by beren12** [comment]
Similar thing here.

**Comment by mdeweerd** [comment]
The title is probably too wide as I guess only the ezsp_backup is giving issues.

You are lucky I have started using an ezsp device myself...

v0.8.21 corrects the ezsp_backup which has some important differences from the znp backup method in zigpy.  

I get a backup in my setup, I have not compared with what I can download using the UI, it looks ok apart from the fact that there are no children at all in the backup file.

**Comment by MattWestb** [comment]
@mdeweerd Bellows is using "hashed TC-Link keys"  = calculated from the joining device IEEE) so its no device token stored for devices but i think one master key is stored as token on the coordinator hardware storage.

I think this is unique for EZSP and the backup is not working restoring on one other coordinator type and standard EZSP firmware is only having 8 key tokens so it can being problem restoring one larger system on one EZSP then link-keys cant being (re)stored.

But the good thing is EZSP have no limited how many device cant being joined (and the joiniee is getting one updated TC-Link key) then using hashed link keys as the other coordinator system is having.

**Comment by tunerooster** [comment]
Thank you!!!  I installed v0.8.22 and the backup now appears to have run successfully.  It created the file:
```
~homeassistant/.homeassistant/custom_components/zha_toolkit/local/nwk_backup_initial.json
```
With the contents:
```
    "node_type": 1,
    "node_id": 0,
    "node_ieee": "80:4b:50:ff:fe:0b:30:ae",
    "panId": 3204,
    "extendedPanId": "cc:cc:cc:cc:a9:a8:cc:84",
    "radioChannel": 11,
    "radioTxPower": 20,
    "nwkUpdateId": 0,
    "channels": 134215680,
    "tc_link_key": {
        "bitmask": 26,
        "type": 1,
        "key": [
            90,
            105,
            103,
            66,
            101,
            101,
            65,
            108,
            108,
            105,
            97,
            110,
            99,
            101,
            48,
            57
        ],
        "outgoingFrameCounter": 2928640,
        "incomingFrameCounter": 0,
        "sequenceNumber": 0,
        "partnerEUI64": "80:4b:50:ff:fe:0b:30:ae"
    },
    "network_key": {
        "bitmask": 3,
        "type": 3,
        "key": [
            161,
            64,
            181,
            254,
            132,
            204,
            168,
            169,
            161,
            64,
            181,
            254,
            132,
            204,
            168,
            169
        ],
        "outgoingFrameCounter": 19353634,
        "incomingFrameCounter": 0,
        "sequenceNumber": 0,
        "partnerEUI64": "00:00:00:00:00:00:00:00"
    },
    "key_table": []
}
```
_Does that appear to be correct?_
I have some 42 zigbee devices and somehow I expected to see the _device names_ and _areas_ backed up, i.e., so I` never have to -by-one reconfigure them again.  _Can you , or anyone, offer me any insight regarding this?_

**Thanks again so much for your help!**

**Comment by mdeweerd** [comment]
As @MattWestb indicated, the individual devices do not appear in the backup.

I downloaded a backup interactively and it turns out that the CLI output format is different and dos not correspond to the "open" format.

![image](https://user-images.githubusercontent.com/1504752/198961965-1e497ac5-31c5-47e7-a1f1-281b041b6a39.png)

I did not find the "entry point" in the zha code part to properly extract the other format.

**Comment by MattWestb** [comment]
One more problem the swapping EZSP coordinators is that the chip IEEE cant being changed like in IT then its onetime burned in the factory.

In the NCP firmware its possible one time writing one new IEEE that the NCP firmware is using and can being done with bellows but it can being redone without one erasing / patching of the token in the user data with one SWD flash tool like Silabs commander, Seeger flasher and so on.

If not changing the IEEE the swapping chip to the original chip some device that have being configured with binding and reporting the the old IEEE is not  working OK until they is reconfigured / updated to the new one.

PS: I swapping NCP of then testing RCP firmware for thread / Zigbee and if i using the same chip for Zigbee NCP and flashing it with RCP all is working OK.

**Comment by tunerooster** [comment]
Is there any way to backup all device/entity ids, friendly names, areas etc.?  I lost everything a while back and it took a lot of time pairing, renaming and reconfiguring everything.  I have been searching for a full zigbee backup/restore procedure ever since and have yet to find a solution.  It is what I was hoping zha_toolkit.backup would do that, but apparently not.  Would anyone here know of such a thing?  Thanks for any suggestions!

**Comment by mdeweerd** [comment]
You can checkout [zha_toolkit.zha_devices](https://github.com/mdeweerd/zha-toolkit#zha_devices-device-list-information-to-event-or-csv) .

It mostly gets the same information that you can view with [zha-network-card](https://github.com/dmulcahey/zha-network-card) and I notice there is a [fork that improves on it](https://github.com/rasmusbe/zha-network-card) .

**Comment by tunerooster** [comment]
Thank you for the advice!  Is there any way to import the data from  zha_toolkit.zha_devices  or zha-network-card after a loss?

**Comment by mdeweerd** [comment]
There is no coded way to reuse that data after a loss.

I am not sure on how that would (have to) work.  
When the configuration is lost, you likely need to pair the devices again.  
At best, you could pair your devices again, and then some program could match the IEEE name to the logged entity name and rename the entity names.
Not sure if there is an official python method for that.
It would have to be coded.
One needs to keep a backup of the extraction of course.

**Comment by tunerooster** [comment]
Thanks again for your reply.  I guess I will have to live with the risk.  Regards!
